[package]
name = "chombot"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
chrono = { version = "0.4.26", features = ["serde"] }
image = { version = "0.24.6", default-features = false, features = ["png"] }
reqwest = "0.11.18"
riichi_hand = "0.3.1"
scraper = "0.16.0"
serde = "1.0.163"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
slug = "0.1.4"
clap = { version = "4.3.0", features = ["derive", "env"] }

[profile.release]
lto = true
