[package]
name = "chombot"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.60"
chrono = { version = "0.4.23", features = ["serde"] }
image = { version = "0.24.5", default-features = false, features = ["png"] }
reqwest = "0.11.13"
riichi_hand = "0.2.0"
scraper = "0.14.0"
selectors = "0.22.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api"] }
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
slug = "0.1.4"

[profile.release]
lto = true
