[package]
name = "chombot"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.56"
chrono = { version = "0.4", features = ["serde"] }
image = { version = "0.24.2", default-features = false, features = ["png"] }
reqwest = "0.11"
riichi_hand = "0.2.0"
scraper = "0.13"
selectors = "0.22.0"
serde = "1.0"
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api"] }
tokio = { version = "1.19", features = ["macros", "rt-multi-thread"] }
slug = "0.1"

[profile.release]
lto = true
