[workspace]
members = [
    "chombot-common",
    "chombot",
    "chombot-kcc"
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true

[workspace.dependencies]
anyhow = "1.0.95"
async-trait = "0.1.83"
chrono = { version = "0.4.39", features = ["serde"] }
reqwest = { version = "0.12.12", features = ["json"] }
riichi_hand = "0.6.3"
scraper = "0.21.0"
serde = "1.0.217"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
slug = "0.1.6"
clap = { version = "4.5.23", features = ["derive", "env"] }
env_logger = "0.11.6"
log = "0.4.22"
num-bigint = "0.4.6"
itertools = "0.13.0"
poise = "0.6.1"
