[workspace]
members = [
    "chombot-common",
    "chombot",
    "chombot-kcc"
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true

[workspace.dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
chrono = { version = "0.4.28", features = ["serde"] }
image = { version = "0.24.7", default-features = false, features = ["png"] }
reqwest = "0.11.22"
riichi_hand = "0.6.0"
scraper = "0.17.1"
serde = "1.0.188"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
slug = "0.1.4"
clap = { version = "4.4.6", features = ["derive", "env"] }
env_logger = "0.10.0"
log = "0.4.20"
num-bigint = "0.4.4"
itertools = "0.11.0"
poise = "0.5.7"
